In [23]:
arr = [1,2,3]
print(arr)
aarr = [x*5 for x in arr]
print(aarr)

[1, 2, 3]
[5, 10, 15]


In [24]:
import numpy as np

In [25]:
# 1d array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.ndim)




[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [26]:
# 2d array

arr2 = np.array([[1,2,3], # row 1
                 [4,5,6] # row 2
                 ])

print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [27]:
# 3d array

arr3 = np.array([
    # 1st floor
    [[1,2,3],
    [4,5,6]],
    
    # 2nd floor
    [[1,2,3],
    [4,5,6]],
    # 3rd
    #  floor
    [[1,2,3],
    [4,5,6]],
])

print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [28]:
# array attributes

# dimension check
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print()

# shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print()

# data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print()

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)
print()

1
2
3

(5,)
(2, 3)
(3, 2, 3)

int64
int64
int64

5
6
18



In [29]:
arr = np.array([1.1,2.2,3.3])
print(arr.dtype)

float64


In [30]:
arr = np.array([1,"s",3.3])
print(arr.dtype)

<U32


In [31]:
# arr = np.array([1.2,2,[1,2,'n'], True])
# print(arr)
# print(arr.dtype)

In [32]:
# nd array creation from existing data

lst = [1,2,3,4.5]
arr = np.array(lst, dtype=np.int64)
print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [33]:
mixed_list = [2, 4.4, True, "nafiz"]
arr = np.array(mixed_list)
print(arr, arr.dtype)

['2' '4.4' 'True' 'nafiz'] <U32


In [34]:
matrix = [[1, 2, 3],
          [4, 5, 6]]

arr = np.array(matrix)
print(arr, arr.dtype, arr.shape, arr.ndim)

[[1 2 3]
 [4 5 6]] int64 (2, 3) 2


In [35]:
tup = (1,2,3)
arr = np.array(tup)
print(arr, arr.dtype, arr.shape, arr.ndim)

[1 2 3] int64 (3,) 1


In [36]:
sett = {1,2,3}
arr = np.array(sett)
# arr = arr.astype(np.int32)
print(arr, arr.dtype, arr.shape, arr.ndim)

{1, 2, 3} object () 0


In [37]:
dc = {'1': 10, '2': 30, '3': 20}
keys = dc.keys()
values = dc.values()
items = dc.items()

arr1 = np.array(list(keys))
arr2 = np.array(list(values))
arr3 = np.array(list(items))

# print(arr1, arr1.dtype, arr1.shape, arr1.ndim, arr1.size)
# print(arr2, arr2.dtype, arr2.shape, arr2.ndim, arr2.size)
print(arr3, arr3.dtype, arr3.shape, arr3.ndim, arr3.size)



[['1' '10']
 ['2' '30']
 ['3' '20']] <U21 (3, 2) 2 6


In [38]:
import numpy as np

In [39]:
# ndarray generation with random values

arr = np.random.uniform(2,20,(3,3), )
# print(arr, arr.dtype, arr.shape, arr.ndim)

arr = np.random.rand(3,3)
# print(arr, arr.dtype, arr.shape, arr.ndim)

arr = np.random.randint(2,30, (1,3))
# print(arr, arr.dtype, arr.shape, arr.ndim)





In [40]:
# array creation with range functions

arr = np.arange(1, 10, 1).reshape(3,3)
# print(arr, arr.dtype, arr.shape, arr.ndim)

arr = np.linspace(1, 10, 11)
# print(arr)

arr = np.logspace(0, 5, 6, base=2)
print(arr)

[ 1.  2.  4.  8. 16. 32.]


In [41]:
# indexing and slicing

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],
        [4,5,6]])

# print(arr1[1:3])
# print(arr2[0:1,])
# print(arr2[1:,])

# print(arr2[:,0:1])
# print(arr2[:,1:2])
# print(arr2[:,2:3])

print(arr2[0:, 0:2])

[[1 2]
 [4 5]]


In [42]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [43]:
arr = np.full((2,2), np.inf)
print(arr)

[[inf inf]
 [inf inf]]


In [44]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]


In [45]:
arr = np.random.rand(2,3)
print(arr)

[[0.78992874 0.90830991 0.89266758]
 [0.4902401  0.08566406 0.38354539]]


In [46]:
arr = np.array([1,2,3,4,5])
arr[1:4] = 0
print(arr)

[1 0 0 0 5]
