In [408]:
import numpy as np

In [409]:
a = np.array([1,2,3])
b = np.array([4,5.4,6])
c = np.array(['nafiz', 3, 4.4, True])


print(a)
print(b)
print(a + b)


[1 2 3]
[4.  5.4 6. ]
[5.  7.4 9. ]


In [410]:
oned = np.array([1,2,3])

twod = np.array([
    [1,2,3],
    [4,5,6]
])

threed = np.array([
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]],
    [[1,2,3], [4,5,6]]
])

In [411]:
print(oned)


[1 2 3]


In [412]:
print(twod)


[[1 2 3]
 [4 5 6]]


In [413]:
print(threed)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [414]:
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)



1
2
3


In [415]:
print(oned.dtype)
print(twod.dtype)
print(threed.dtype)



int64
int64
int64


In [416]:
print(oned.size)
print(twod.size)
print(threed.size)



3
6
18


In [417]:
print(b.dtype)

float64


In [418]:
print(c.dtype)

<U32


In [419]:
setted_npdata = np.array([1,2,'3'], dtype=np.float64)
print(setted_npdata.dtype)

setted_npdata_cpy = setted_npdata.astype(np.int32)
print(setted_npdata_cpy.dtype)


float64
int32


In [420]:
lst = [1,2,3,45]
nplst = np.array(lst)
print(type(lst))
print(type(nplst.dtype))

<class 'list'>
<class 'numpy.dtypes.Int64DType'>


In [421]:
matrix = [
    [1,2,3],
    [4,5,6]
]

arr_matrix = np.array(matrix, dtype=np.float32)
print(matrix)
print(arr_matrix)

print(type(matrix))
print(arr_matrix.ndim)
print(arr_matrix.shape)



[[1, 2, 3], [4, 5, 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
<class 'list'>
2
(2, 3)


In [422]:
st = {1,2,3}
st_array = np.array(list(st))

print(st_array.dtype)
print(st_array.ndim)
print(st_array.shape)
print(st_array.size)



int64
1
(3,)
3


In [423]:
dick = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
print(dick)
print(type(dick))

array_dick1 = np.array(list(dick.keys()))
array_dick2 = np.array(list(dick.values()))
array_dick3 = np.array(list(dick.items()))

print(array_dick1)
print(array_dick2)
print(array_dick3)

print(array_dick1.ndim)
print(array_dick2.ndim)
print(array_dick3.ndim)

print(array_dick1.size)
print(array_dick2.size)
print(array_dick3.size)

print(array_dick3.dtype)
print(array_dick2.dtype)
print(array_dick1.dtype)


{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
<class 'dict'>
['a' 'b' 'c' 'd' 'e']
[1 2 3 4 5]
[['a' '1']
 ['b' '2']
 ['c' '3']
 ['d' '4']
 ['e' '5']]
1
1
2
5
5
10
<U21
int64
<U1


In [424]:
arr = np.zeros((3,3))
arr = arr.astype(np.int16)

print(arr)
print(arr.dtype)

arr2 = np.zeros_like(arr)
print(arr2)
print(arr2.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int16
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int16


In [425]:
arr = np.ones((3,3), dtype=np.int16)
print(arr)

arr2 = np.ones_like(arr)
print(arr2)
print(arr2.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
int16


In [426]:
arr = np.empty((3,3), dtype=np.int8)
print(arr)

arr2 = np.empty_like(arr)
print(arr2)
print(arr2.dtype)

[[0 0 1]
 [0 1 0]
 [0 0 0]]
[[0 0 1]
 [0 1 0]
 [0 0 0]]
int8


In [427]:
arr = np.full((3,3), fill_value=1)
arr2 = np.full((3,3), np.inf)

print(arr)
print(arr2)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [428]:
arr = np.full((3,3), np.inf)
print(arr)
arr2 = np.full_like(arr, np.inf, dtype=np.float32)
print(arr2)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [429]:
arr = np.random.rand(3,3)
print(arr)


[[0.01468091 0.42453084 0.87094029]
 [0.71869836 0.87210296 0.61113587]
 [0.95598952 0.29564526 0.05017486]]


In [430]:
arr = np.random.randint(1, 10, (3, 3, 3))
print(arr)

[[[1 9 5]
  [2 1 8]
  [3 9 2]]

 [[7 6 4]
  [1 8 9]
  [4 7 2]]

 [[8 1 3]
  [7 6 7]
  [2 7 5]]]


In [431]:
arr = np.random.uniform(1,5, (3,3,3))
print(arr)

[[[4.38628831 2.26324318 1.92508303]
  [1.89006312 4.71441228 3.87452221]
  [3.56378026 1.43255498 4.51223616]]

 [[2.1863485  4.49046204 3.4590774 ]
  [4.32069471 4.1468933  2.65141074]
  [1.48130497 2.35158675 1.52534749]]

 [[1.01689618 1.02082828 2.68003839]
  [3.51265105 1.80128282 4.76312824]
  [4.32151372 2.82913113 2.01495462]]]


In [432]:
arr = np.arange(1,17)
print(arr)

reshape_arr = arr.reshape(4,4)
print(reshape_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [433]:
arr = np.linspace(1,2,5, dtype=np.float32)
print(arr)

[1.   1.25 1.5  1.75 2.  ]


In [434]:
arr = np.logspace(10,20,5,base=1000)
print(arr)

[1.00000000e+30 3.16227766e+37 1.00000000e+45 3.16227766e+52
 1.00000000e+60]


In [435]:
diad_mattrix = np.diag([1,2,1,2])
print(diad_mattrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 2]]


In [436]:
identity_matrix = np.eye(4)
print(identity_matrix)

identity_matrix = np.eye(3,2)
print(identity_matrix)

identity_matrix = np.eye(4,5,1)
print(identity_matrix)

identity_matrix = np.eye(4,4,-2)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [437]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

In [438]:
print(arr1)
print(arr2)


[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [439]:
arr1[2] = 100
print(arr1)

arr2[1][2] = 100
print(arr1)

[  1   2 100   4]
[  1   2 100   4]


In [440]:
print(arr1)
print(arr2)

[  1   2 100   4]
[[  1   2   3]
 [  4   5 100]]


In [441]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

In [442]:
print(arr2[1:2])


[[4 5 6]]


In [443]:
print(arr2[:,0:2])

[[1 2]
 [4 5]]


In [444]:
lst = np.array([1,2,30,4,50])
lst_of_lst = lst[[0,1,4]]
print(lst)
print(lst_of_lst)



[ 1  2 30  4 50]
[ 1  2 50]


In [445]:
arr = np.array([
    [7, 2, 3, 3],
 [3, 6, 3, 5],
 [2, 7, 5, 2]
])
# print(arr)
print(arr[[0,1], [1,3]])
arr[arr < 0] = 402
print(arr)
print(arr[arr > 4])

[2 5]
[[7 2 3 3]
 [3 6 3 5]
 [2 7 5 2]]
[7 6 5 7 5]


In [446]:
iter_arr = np.array([
    [[1, 2, 3],
  [4, 5, 6]],
 [[7, 8, 9],
  [10, 11, 12]]
])
print(iter_arr.ndim)

for i in np.nditer(iter_arr):
  print(i, end=" ")

3
1 2 3 4 5 6 7 8 9 10 11 12 

In [447]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

arr_reshape = arr.reshape(2,3)
print(arr_reshape)

(6,)
[[1 2 3]
 [4 5 6]]


In [448]:
arr = np.arange(6)
arr2 = arr.reshape(3, 2)
print(arr2)

arr.resize(2, 3)
print(arr)


[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [449]:
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)
flat1 = arr.flatten()
flat2 = arr.ravel()
print("Flatten result:", flat1, type(flat1), flat1.ndim, flat1.dtype)
print("Ravel result:", flat2, type(flat2), flat2.ndim, flat2.dtype)


2
Flatten result: [1 2 3 4] <class 'numpy.ndarray'> 1 int64
Ravel result: [1 2 3 4] <class 'numpy.ndarray'> 1 int64


In [450]:
arr = np.array([[10, 20], [30, 40]])
r = arr.flatten()
r[0] = 999
print("Modified flatten array:", r)
print("Original array also changes:", arr)


Modified flatten array: [999  20  30  40]
Original array also changes: [[10 20]
 [30 40]]


In [451]:
arr = np.array([[10, 20], [30, 40]])
r = arr.ravel()
r[0] = 999
print("Modified ravel array:", r)
print("Original array also changes:", arr)


Modified ravel array: [999  20  30  40]
Original array also changes: [[999  20]
 [ 30  40]]


In [452]:
arr = np.array([1, 2, 3])
print(arr.shape)

expanded = np.expand_dims(arr, axis=0)
print(expanded.shape)

arr = np.squeeze(arr)
print(arr.shape)

expanded1 = np.expand_dims(arr, axis=1)
print(expanded1.shape)

arr = np.squeeze(arr)
print(arr.shape)

(3,)
(1, 3)
(3,)
(3, 1)
(3,)


In [453]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b)))
print(np.hstack((a, b)))
print(np.vstack((a, b)))


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [454]:
arr = np.arange(20)
print(np.split(arr, [4, 6]))

[array([0, 1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]


In [455]:
arr = np.array([12,3,4,5])
print(arr)

arr = np.insert(arr, 3,5000)
print(arr)

[12  3  4  5]
[  12    3    4 5000    5]


In [456]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.transpose(arr, axes=(0,1)))


[[1 2 3]
 [4 5 6]]


In [457]:
a = np.array([12,3,4,5])
b = a.view()
print(a)
print(b)

print(id(a))
print(id(b))


[12  3  4  5]
[12  3  4  5]
132156287160496
132156288620976


In [458]:
X = np.arange(12)
X = X.reshape(3, -1)
print(X)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [459]:
arr = np.array([1, 2, 3])
print(np.exp(arr))# e^x
print(np.log(arr))# natural log
print(np.log10(arr))# base-10 log


[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]


In [460]:
arr = np.array([1, 2, 3])
tiled = np.tile(arr, (3, 3))
print(tiled)


[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [461]:
data = np.array([45, 50, np.nan, 60, 30])
valid = np.logical_and(~np.isnan(data), data >= 50)
print(data)
print(valid)
filtered_data = data[valid]
print(filtered_data)


[45. 50. nan 60. 30.]
[False  True False  True False]
[50. 60.]


In [462]:
arr = np.array([
    [22,4,51],
    [45,576,78]
])

print(np.sort(arr, axis=1))
print(np.sort(arr, axis=0))


[[  4  22  51]
 [ 45  78 576]]
[[ 22   4  51]
 [ 45 576  78]]


In [463]:
arr = np.array([50, 10, 30, 20])
indices = np.argsort(arr)
print(indices)
print(arr[indices])


[1 3 2 0]
[10 20 30 50]


In [464]:
data = np.array([("Alice", 25), ("Bob", 30), ("Charlie", 20)], dtype=[('name', 'U10'), ('age', 'i4')])
print(np.sort(data, order='age'))


[('Charlie', 20) ('Alice', 25) ('Bob', 30)]


In [465]:
arr = np.array([3, 7, 3, 2, 9, 3])
indices = np.where(arr != 3)
print(indices)
print(arr[indices])



(array([1, 3, 4]),)
[7 2 9]


In [466]:
arr = np.array([10, 20, 30, 40, 50])
pos = np.searchsorted(arr, 35)
print(pos)
print(arr)
print(pos)

3
[10 20 30 40 50]
3


In [467]:
arr = np.array([1, 2, 1, 3,3,3,3,3, 2, 1])
unique, counts = np.unique(arr, return_counts=True)
print(unique)
print(counts)


[1 2 3]
[3 2 5]


In [468]:
arr = np.array([1000,20,3000,40,500])
print(arr)

[1000   20 3000   40  500]


In [469]:
# mean_value = arr.mean()
mean_value = np.mean(arr)
print(mean_value)

912.0


In [470]:
# arr = np.array([
#     [1,2,3],
#     [4,5,6]
# ])
# col_mean = np.mean(arr, axis=0)
# row_mean = np.mean(arr, axis=1)
# print(col_mean)
# print(row_mean)



In [471]:
emdian_value = np.median(arr)
print(emdian_value)

500.0
