In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 100, size=(10,5))
arr.shape

(10, 5)

In [3]:
b = arr.reshape(5, 10)
x = arr.reshape(2, 25) # can't re shape

# print(x)
# b.shape
# b.ndim
flatten = b.flatten()
print(flatten)
# flatten.ndim

[18 72 67 30 92 28 63 27  7 81 32 76 94 73 21 74 21 33  4 90 88 83 56 86
 78 28 95 80 51 32 51 17 82  8 92 28 36 96 74 60 53 87 31 25 33 70 78 93
 81  3]


In [4]:
b

array([[18, 72, 67, 30, 92, 28, 63, 27,  7, 81],
       [32, 76, 94, 73, 21, 74, 21, 33,  4, 90],
       [88, 83, 56, 86, 78, 28, 95, 80, 51, 32],
       [51, 17, 82,  8, 92, 28, 36, 96, 74, 60],
       [53, 87, 31, 25, 33, 70, 78, 93, 81,  3]], dtype=int32)

In [5]:
column_flatten = np.ravel(b, order='F')
column_flatten

array([18, 32, 88, 51, 53, 72, 76, 83, 17, 87, 67, 94, 56, 82, 31, 30, 73,
       86,  8, 25, 92, 21, 78, 92, 33, 28, 74, 28, 28, 70, 63, 21, 95, 36,
       78, 27, 33, 80, 96, 93,  7,  4, 51, 74, 81, 81, 90, 32, 60,  3],
      dtype=int32)

In [6]:
a = np.random.randint(1, 10, size=(3,3))
b = np.random.randint(20, 30, size=(1,3))

print(a)
print(b)

con = np.concatenate((a, b), axis=0)
print(con)

[[7 3 3]
 [7 5 1]
 [9 4 4]]
[[23 23 28]]
[[ 7  3  3]
 [ 7  5  1]
 [ 9  4  4]
 [23 23 28]]


In [7]:
arr = np.array([[1,2,3,4], [9,8,7,6]])

print(arr)

transpose = arr.T
print(transpose)

[[1 2 3 4]
 [9 8 7 6]]
[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [8]:
# array split

arr = np.random.randint(1, 10, size=(10,))
split_arr = np.array_split(arr, 3) 
# split_arr = np.split(arr, 3) # for equal division

print(arr)
print(split_arr)

[9 5 6 8 8 9 1 2 3 4]
[array([9, 5, 6, 8], dtype=int32), array([8, 9, 1], dtype=int32), array([2, 3, 4], dtype=int32)]


In [9]:
# x = [10,20,30,40,50]
# y = [2,3,4,5]
# add = x + y
# add

x = np.array([1,4,9,16])
y = np.array([2,3,4,5])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x % y)


[ 3  7 13 21]
[-1  1  5 11]
[ 2 12 36 80]
[0.5        1.33333333 2.25       3.2       ]
[0 1 2 3]
[1 1 1 1]


In [10]:
# mathmathical function

# trigonomatry
# sin, cos, tan takes values in radian

sin_val = np.sin(x)
cos_val = np.cos(x)
tan_val = np.tan(x)

print(sin_val)
print(cos_val)
print(tan_val)

# deg to rad or rad to deg convestion

deg_con = np.rad2deg(x)
print(deg_con)

rad_con = np.deg2rad(deg_con)
print(rad_con)

[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
[ 1.55740772  1.15782128 -0.45231566  0.30063224]
[ 57.29577951 229.18311805 515.66201562 916.73247221]
[ 1.  4.  9. 16.]


In [11]:
# log
base_10_log = np.log10(x)
# print(base_10_log)

base_2_diye_vag = np.log2(x)
# print(base_2_diye_vag)

sqrt = np.sqrt(x)
# print(sqrt)

In [12]:
# different

jog = np.sum(x)
cum_jog = np.cumsum(x)

print(jog)
print(cum_jog)

30
[ 1  5 14 30]


In [13]:
# logical functions

x = np.array([10, 8, 16, 100])
y = np.array([2, 8, 4, 500])

greater_than = x > y
equal = x == y
print(greater_than)
print(equal) 

# all
# to check sob trrue kina
# any 
# to check jekono ekta true kina

print(np.all(greater_than))
print(np.any(greater_than))


[ True False  True False]
[False  True False False]
False
True


In [14]:
x = np.array([10, 8, 16, 100])
z = x.copy()
print(x)
z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]
