In [30]:
import numpy as np

In [31]:
array = np.arange(11, 50, 2)
print(array)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [32]:
fxf_matrix = np.random.randint(0, 15, (4, 4))
print(fxf_matrix)
print()
print(fxf_matrix[0:1,:])
print(fxf_matrix[:,3:])

[[ 8 10  4  5]
 [ 0  4  6  9]
 [ 6 11  8 12]
 [14 11 13  0]]

[[ 8 10  4  5]]
[[ 5]
 [ 9]
 [12]
 [ 0]]


In [33]:
print(fxf_matrix[1:3,1:3])
print((fxf_matrix[1:3,1:3]).shape)


[[ 4  6]
 [11  8]]
(2, 2)


In [34]:
zero = np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
ones = np.ones((2,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
seven = np.full((3,3), 7)
print(seven)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
