In [43]:
import numpy as np

In [44]:
arr = [1,2,3]
print(arr * 5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [45]:
arr = np.array([1,2,3])
print(arr * 5)

[ 5 10 15]


In [46]:
arr1 = np.array([1,2,3])
print(arr1.ndim)
print(arr1.dtype)
print(arr1.shape)

1
int64
(3,)


In [47]:
arr2 = np.array([[1,2,3],[1,2,3]])
print(arr2.ndim)
print(arr2.dtype)
print(arr2.shape)

2
int64
(2, 3)


In [48]:
arr3 = np.array([[[1,2], [3,4]], [[1,2],[3,4]]])
print(arr3.ndim)
print(arr3.dtype)
print(arr3.shape)

3
int64
(2, 2, 2)


In [49]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [50]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
dtypee.astype(np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [51]:
arr = np.array([1,'2', 3.3, True])
print(arr.dtype)
print(arr)

<U32
['1' '2' '3.3' 'True']


In [52]:
lst = [10,20,30,40.7]
arr = np.array(lst)
arr = arr.astype(np.int32)
print(arr)
print(arr.dtype)
print(type(arr))

[10 20 30 40]
int32
<class 'numpy.ndarray'>


In [53]:
tpl = (1,2,3,4,5)
tpl = np.array(tpl)
print(type(tpl))
print(tpl.dtype)
print(tpl.ndim)
print(tpl.shape)

<class 'numpy.ndarray'>
int64
1
(5,)


In [54]:
st = {1,2,3,4}
st = np.array((st))
print(type(st))
print(st.dtype)
print(st.ndim)
print(st.shape)

<class 'numpy.ndarray'>
object
0
()


In [55]:
dc = {'a': 10, 'b': 20, 'c': 30}

key = dc.keys()
value = dc.values()
item = dc.items()

k = np.array(key)
print(type(k))
print(k)

v = np.array(value)
print(type(v))
print(v)

i = np.array(list(item))
print(type(i))
print(i)


<class 'numpy.ndarray'>
dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
dict_values([10, 20, 30])
<class 'numpy.ndarray'>
[['a' '10']
 ['b' '20']
 ['c' '30']]


In [56]:
arr = np.random.rand(3,3) 
print(arr)
print(arr.dtype)

[[0.58818449 0.98319447 0.6874967 ]
 [0.53778265 0.04240123 0.17025402]
 [0.8543616  0.74895715 0.27802016]]
float64


In [57]:
arr = np.random.randint(1, 10, (10,10))
print(arr)
print(arr.dtype)

[[9 9 2 2 1 8 5 9 8 9]
 [6 2 5 9 8 4 1 1 4 1]
 [7 3 4 7 4 2 6 5 3 2]
 [3 8 2 3 9 8 8 5 6 5]
 [4 9 1 5 6 6 3 3 1 9]
 [8 1 2 6 2 5 9 2 3 6]
 [7 5 8 8 9 7 1 2 1 3]
 [4 4 3 2 4 1 9 7 9 9]
 [7 9 5 7 2 1 6 1 7 7]
 [5 2 2 5 9 4 5 3 3 6]]
int32


In [58]:
arr = np.random.uniform(1, 10, (3,3))
print(arr)
print(arr.dtype)

[[5.39627799 5.16069608 5.76869511]
 [7.95263607 4.11316203 9.91946267]
 [7.36396212 4.15178741 2.37827893]]
float64


In [59]:
arr = np.arange(1,10, 3).reshape(3,)
print(arr)

[1 4 7]


In [60]:
arr = np.linspace(1, 10, 19)
print(arr)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [61]:
arr = np.logspace(0, 4, 5, base=8)
print(arr)

[1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]


In [62]:
arr = np.array([1,2,3,4,5])
print(arr[::])

[1 2 3 4 5]


In [63]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[0][1])

print(arr2[0:,0:2])

print(arr2[::-1,::-1])

2
[[1 2]
 [4 5]]
[[6 5 4]
 [3 2 1]]


In [64]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[::-1,::-1])

[[6 5 4]
 [3 2 1]]


In [65]:
arr2[:,:1]

array([[1],
       [4]])

In [66]:
arr = np.array([[1,2],
               [3,4]])

arr[0:1, 1:] == 300
print(arr)

[[1 2]
 [3 4]]


In [67]:
arr = np.array([1,2,3,4])
arr2 = arr[1:3].copy()
# arr2 = arr[1:3]


print(arr)
print(arr2)

arr2[1:2] = 100

print(arr)
print(arr2)

[1 2 3 4]
[2 3]
[1 2 3 4]
[  2 100]


In [68]:
lst = np.array([1,2,3,4,4])
values = lst[[2,3,3]]
print(lst)
print(values)

[1 2 3 4 4]
[3 4 4]


In [69]:
twod = np.array([[1,8,9],
                 [6,3,4]])
print(twod[1:,1:2])

[[3]]


In [70]:
print(lst[lst > 2])

[3 4 4]


In [71]:
arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)
    print(i)

1
2
3
[1 2 3]
4
5
6
[4 5 6]


In [72]:
arr = np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [73]:
data = [1,2,3,4,5]
temp_in_cel = np.array(data)
print(temp_in_cel * 1.8 + 32)

[33.8 35.6 37.4 39.2 41. ]


In [74]:
data = [1,2,3,4,5]
lap_times = np.array(data)
lap_times_in_minute = np.round((lap_times / 60).copy(),2)
print(lap_times)
print(lap_times_in_minute)

[1 2 3 4 5]
[0.02 0.03 0.05 0.07 0.08]


In [75]:
arr = np.random.randint(1,99, size=(10,5))
print(arr)

[[22 10 76 52 95]
 [52 80  9 34 95]
 [26  1 69 48 65]
 [66 29 68 26 94]
 [73 79 49 97 81]
 [50 27 10 59 57]
 [97 74 49 58 73]
 [56 39 80 21 61]
 [17 32 15 43  5]
 [49 45 85 41 14]]


In [76]:
print(arr.shape)
print(arr)
arr = arr.reshape(5,10) 
print(arr.shape)
print(arr)


(10, 5)
[[22 10 76 52 95]
 [52 80  9 34 95]
 [26  1 69 48 65]
 [66 29 68 26 94]
 [73 79 49 97 81]
 [50 27 10 59 57]
 [97 74 49 58 73]
 [56 39 80 21 61]
 [17 32 15 43  5]
 [49 45 85 41 14]]
(5, 10)
[[22 10 76 52 95 52 80  9 34 95]
 [26  1 69 48 65 66 29 68 26 94]
 [73 79 49 97 81 50 27 10 59 57]
 [97 74 49 58 73 56 39 80 21 61]
 [17 32 15 43  5 49 45 85 41 14]]
