In [104]:
import numpy as np

In [105]:
arr = [1,2,3]
print(arr * 5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [106]:
arr = np.array([1,2,3])
print(arr * 5)

[ 5 10 15]


In [107]:
arr1 = np.array([1,2,3])
print(arr1.ndim)
print(arr1.dtype)
print(arr1.shape)

1
int64
(3,)


In [108]:
arr2 = np.array([[1,2,3],[1,2,3]])
print(arr2.ndim)
print(arr2.dtype)
print(arr2.shape)

2
int64
(2, 3)


In [109]:
arr3 = np.array([[[1,2], [3,4]], [[1,2],[3,4]]])
print(arr3.ndim)
print(arr3.dtype)
print(arr3.shape)

3
int64
(2, 2, 2)


In [110]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [111]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
dtypee.astype(np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [112]:
arr = np.array([1,'2', 3.3, True])
print(arr.dtype)
print(arr)

<U32
['1' '2' '3.3' 'True']


In [113]:
lst = [10,20,30,40.7]
arr = np.array(lst)
arr = arr.astype(np.int32)
print(arr)
print(arr.dtype)
print(type(arr))

[10 20 30 40]
int32
<class 'numpy.ndarray'>


In [114]:
tpl = (1,2,3,4,5)
tpl = np.array(tpl)
print(type(tpl))
print(tpl.dtype)
print(tpl.ndim)
print(tpl.shape)

<class 'numpy.ndarray'>
int64
1
(5,)


In [115]:
st = {1,2,3,4}
st = np.array((st))
print(type(st))
print(st.dtype)
print(st.ndim)
print(st.shape)

<class 'numpy.ndarray'>
object
0
()


In [116]:
dc = {'a': 10, 'b': 20, 'c': 30}

key = dc.keys()
value = dc.values()
item = dc.items()

k = np.array(key)
print(type(k))
print(k)

v = np.array(value)
print(type(v))
print(v)

i = np.array(list(item))
print(type(i))
print(i)


<class 'numpy.ndarray'>
dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
dict_values([10, 20, 30])
<class 'numpy.ndarray'>
[['a' '10']
 ['b' '20']
 ['c' '30']]


In [117]:
arr = np.random.rand(3,3) 
print(arr)
print(arr.dtype)

[[0.69498399 0.14472361 0.87420402]
 [0.03827921 0.31549319 0.09373534]
 [0.51314397 0.75393091 0.56851503]]
float64


In [118]:
arr = np.random.randint(1, 10, (10,10))
print(arr)
print(arr.dtype)

[[7 2 4 6 8 9 4 2 9 4]
 [7 9 2 5 9 2 8 6 5 4]
 [7 5 9 5 3 5 7 1 9 8]
 [7 2 5 1 5 9 1 4 5 8]
 [5 7 4 4 1 6 1 6 3 8]
 [3 1 2 8 6 1 7 2 3 3]
 [9 2 5 6 1 3 6 3 8 8]
 [8 7 1 4 4 7 2 7 4 3]
 [7 9 8 9 9 5 6 4 9 6]
 [3 2 4 2 9 3 7 7 2 1]]
int32


In [119]:
arr = np.random.uniform(1, 10, (3,3))
print(arr)
print(arr.dtype)

[[7.80118477 2.51797243 4.13147061]
 [9.62384185 8.17809093 2.67486921]
 [7.74478244 9.57934788 4.70584476]]
float64


In [120]:
arr = np.arange(1,10, 3).reshape(3,)
print(arr)

[1 4 7]


In [121]:
arr = np.linspace(1, 10, 19)
print(arr)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [122]:
arr = np.logspace(0, 4, 5, base=8)
print(arr)

[1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]


In [123]:
arr = np.array([1,2,3,4,5])
print(arr[::])

[1 2 3 4 5]


In [124]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[0][1])

print(arr2[0:,0:2])

print(arr2[::-1,::-1])

2
[[1 2]
 [4 5]]
[[6 5 4]
 [3 2 1]]


In [125]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[::-1,::-1])

[[6 5 4]
 [3 2 1]]


In [126]:
arr2[:,:1]

array([[1],
       [4]])

In [127]:
arr = np.array([[1,2],
               [3,4]])

arr[0:1, 1:] == 300
print(arr)

[[1 2]
 [3 4]]


In [128]:
arr = np.array([1,2,3,4])
arr2 = arr[1:3].copy()
# arr2 = arr[1:3]


print(arr)
print(arr2)

arr2[1:2] = 100

print(arr)
print(arr2)

[1 2 3 4]
[2 3]
[1 2 3 4]
[  2 100]


In [129]:
lst = np.array([1,2,3,4,4])
values = lst[[2,3,3]]
print(lst)
print(values)

[1 2 3 4 4]
[3 4 4]


In [130]:
twod = np.array([[1,8,9],
                 [6,3,4]])
print(twod[1:,1:2])

[[3]]


In [131]:
print(lst[lst > 2])

[3 4 4]


In [132]:
arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)
    print(i)

1
2
3
[1 2 3]
4
5
6
[4 5 6]


In [133]:
arr = np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [134]:
data = [1,2,3,4,5]
temp_in_cel = np.array(data)
print(temp_in_cel * 1.8 + 32)

[33.8 35.6 37.4 39.2 41. ]


In [135]:
data = [1,2,3,4,5]
lap_times = np.array(data)
lap_times_in_minute = np.round((lap_times / 60).copy(),2)
print(lap_times)
print(lap_times_in_minute)

[1 2 3 4 5]
[0.02 0.03 0.05 0.07 0.08]


In [136]:
arr = np.random.randint(1,99, size=(10,5))
print(arr)

[[33  8 62 43 90]
 [ 3 21 35 45 42]
 [ 4 58 55 37 40]
 [94 18 93  2 14]
 [34 67 64 61 85]
 [81 94 19 21 60]
 [13 47 59 50 18]
 [16 38 96 65 21]
 [42 42 19  8 82]
 [79 45 83 28 54]]


In [137]:
print(arr.shape)
print(arr)
arr = arr.reshape(5,10) 
print(arr.shape)
print(arr)


(10, 5)
[[33  8 62 43 90]
 [ 3 21 35 45 42]
 [ 4 58 55 37 40]
 [94 18 93  2 14]
 [34 67 64 61 85]
 [81 94 19 21 60]
 [13 47 59 50 18]
 [16 38 96 65 21]
 [42 42 19  8 82]
 [79 45 83 28 54]]
(5, 10)
[[33  8 62 43 90  3 21 35 45 42]
 [ 4 58 55 37 40 94 18 93  2 14]
 [34 67 64 61 85 81 94 19 21 60]
 [13 47 59 50 18 16 38 96 65 21]
 [42 42 19  8 82 79 45 83 28 54]]


In [138]:
arr.ndim

2

In [139]:
flatt = arr.flatten()

In [140]:
flatt.ndim

1

In [141]:
print(arr)

[[33  8 62 43 90  3 21 35 45 42]
 [ 4 58 55 37 40 94 18 93  2 14]
 [34 67 64 61 85 81 94 19 21 60]
 [13 47 59 50 18 16 38 96 65 21]
 [42 42 19  8 82 79 45 83 28 54]]


In [142]:
print(flatt)

[33  8 62 43 90  3 21 35 45 42  4 58 55 37 40 94 18 93  2 14 34 67 64 61
 85 81 94 19 21 60 13 47 59 50 18 16 38 96 65 21 42 42 19  8 82 79 45 83
 28 54]


In [143]:
rav = np.ravel(arr, order='K')

In [144]:
print(rav)

[33  8 62 43 90  3 21 35 45 42  4 58 55 37 40 94 18 93  2 14 34 67 64 61
 85 81 94 19 21 60 13 47 59 50 18 16 38 96 65 21 42 42 19  8 82 79 45 83
 28 54]


In [145]:
a = np.random.randint(1, 10, (2,3))
b = np.random.randint(11, 20, (2,3))
print(a)
print(b)

[[9 5 7]
 [3 2 1]]
[[18 15 12]
 [18 15 18]]


In [146]:
con = np.concatenate((a, b), axis=1)
print(con)

[[ 9  5  7 18 15 12]
 [ 3  2  1 18 15 18]]


In [147]:
con = np.concatenate((a, b), axis=0)
print(con)

[[ 9  5  7]
 [ 3  2  1]
 [18 15 12]
 [18 15 18]]


In [148]:
mat = np.array([
    [1,2,3],
    [4,5,6]
])

transpost = mat.T
transpost

array([[1, 4],
       [2, 5],
       [3, 6]])

In [149]:
a = np.random.randint(1, 10, (9,))
print(a)

[1 6 7 4 6 1 7 4 8]


In [150]:
split_arr = np.array_split(a, 3) 
print(split_arr)

[array([1, 6, 7], dtype=int32), array([4, 6, 1], dtype=int32), array([7, 4, 8], dtype=int32)]


In [151]:
split_arr = np.split(a, 3)
print(split_arr)

[array([1, 6, 7], dtype=int32), array([4, 6, 1], dtype=int32), array([7, 4, 8], dtype=int32)]


In [152]:
a

array([1, 6, 7, 4, 6, 1, 7, 4, 8], dtype=int32)

In [153]:
sinn = np.sin(a)
sinn

array([ 0.84147098, -0.2794155 ,  0.6569866 , -0.7568025 , -0.2794155 ,
        0.84147098,  0.6569866 , -0.7568025 ,  0.98935825])

In [154]:
coss = np.cos(a)
coss

array([ 0.54030231,  0.96017029,  0.75390225, -0.65364362,  0.96017029,
        0.54030231,  0.75390225, -0.65364362, -0.14550003])

In [155]:
degtored = np.rad2deg(a)
degtored

array([ 57.29577951, 343.77467708, 401.07045659, 229.18311805,
       343.77467708,  57.29577951, 401.07045659, 229.18311805,
       458.3662361 ])

In [156]:
ten_base_log = np.log10(a)
ten_base_log

array([0.        , 0.77815125, 0.84509804, 0.60205999, 0.77815125,
       0.        , 0.84509804, 0.60205999, 0.90308999])

In [157]:
two_base_log = np.log2(a)
print(two_base_log)

[0.         2.5849625  2.80735492 2.         2.5849625  0.
 2.80735492 2.         3.        ]


In [158]:
sqrt = np.sqrt(a)
print(sqrt)

[1.         2.44948974 2.64575131 2.         2.44948974 1.
 2.64575131 2.         2.82842712]


In [159]:
x = np.array([10,800,16,100])
y = np.array([2,3,4,5])
print(x < y)
print(x > y)
print(x == y)


[False False False False]
[ True  True  True  True]
[False False False False]


In [160]:
print(np.all(x>y))

True


In [161]:
x

array([ 10, 800,  16, 100])

In [162]:
z = x.copy()

In [163]:
z

array([ 10, 800,  16, 100])

In [164]:
z.sort()
z

array([ 10,  16, 100, 800])

In [165]:
x

array([ 10, 800,  16, 100])

In [166]:
x

array([ 10, 800,  16, 100])

In [167]:
z

array([ 10,  16, 100, 800])

In [168]:
sort_arr = np.sort(x)
sort_arr

array([ 10,  16, 100, 800])

In [169]:
x

array([ 10, 800,  16, 100])

In [170]:
z

array([ 10,  16, 100, 800])

In [171]:
mat = np.array([[1,30,9],
               [5,4,8]])
hor_sort = np.sort(mat, axis=1)
print(hor_sort)
print()
ver_sort = np.sort(mat, axis=0)
print(ver_sort)

[[ 1  9 30]
 [ 4  5  8]]

[[ 1  4  8]
 [ 5 30  9]]


In [172]:
x

array([ 10, 800,  16, 100])

In [173]:
print(x)

[ 10 800  16 100]


In [174]:
index = np.where(x>8)
print(index)


(array([0, 1, 2, 3]),)


In [175]:
index = np.where(x>8, x, 0)
print(index)


[ 10 800  16 100]


In [176]:
mat

array([[ 1, 30,  9],
       [ 5,  4,  8]])

In [177]:
index = np.where(mat > 5)

In [178]:
index

(array([0, 0, 1]), array([1, 2, 2]))

In [179]:
index = np.where(mat<8, mat, 0)
print(index)

[[1 0 0]
 [5 4 0]]


In [180]:
x

array([ 10, 800,  16, 100])

In [182]:
index = np.argmax(x)
print(index)
print(x[index])

1
800


In [183]:
index = np.argmin(x)
print(index)
print(x[index])

0
10


In [186]:
rand = np.random.randint(1,100,size=100)

In [188]:
print(rand)

[87 27 66 27 52 66 21  5 60 23 38 78 56  4 51 56 27 99 34  9 86 88 99 42
 91  9 58 58 33 75 77 15 35 54 21 84 64 88 66 85 97 83 44 49 26  5 46 42
 57 98 27 37 64 60 50 16 83 87 34 21 62 67 46 80  1 29 19 32 81 70 98 15
 56  6 59 84 44 10 35 61  7 84 63 33 47 63 53 91 54 41 84 85 28  3 19 35
 21 13 69 42]


In [196]:
count_number = np.count_nonzero(rand==70)
print(count_number)

1


In [198]:
uniq = np.unique(rand, return_counts = True)
print(uniq)

(array([ 1,  3,  4,  5,  6,  7,  9, 10, 13, 15, 16, 19, 21, 23, 26, 27, 28,
       29, 32, 33, 34, 35, 37, 38, 41, 42, 44, 46, 47, 49, 50, 51, 52, 53,
       54, 56, 57, 58, 59, 60, 61, 62, 63, 64, 66, 67, 69, 70, 75, 77, 78,
       80, 81, 83, 84, 85, 86, 87, 88, 91, 97, 98, 99], dtype=int32), array([1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 4, 1, 1, 4, 1, 1, 1, 2, 2, 3,
       1, 1, 1, 3, 2, 2, 1, 1, 1, 1, 1, 1, 2, 3, 1, 2, 1, 2, 1, 1, 2, 2,
       3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 2, 1, 2, 2, 2, 1, 2, 2]))
