In [1]:
import numpy as np

In [2]:
arr = [1,2,3]
print(arr * 5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [3]:
arr = np.array([1,2,3])
print(arr * 5)

[ 5 10 15]


In [4]:
arr1 = np.array([1,2,3])
print(arr1.ndim)
print(arr1.dtype)
print(arr1.shape)

1
int64
(3,)


In [5]:
arr2 = np.array([[1,2,3],[1,2,3]])
print(arr2.ndim)
print(arr2.dtype)
print(arr2.shape)

2
int64
(2, 3)


In [6]:
arr3 = np.array([[[1,2], [3,4]], [[1,2],[3,4]]])
print(arr3.ndim)
print(arr3.dtype)
print(arr3.shape)

3
int64
(2, 2, 2)


In [7]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [8]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
dtypee.astype(np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [9]:
arr = np.array([1,'2', 3.3, True])
print(arr.dtype)
print(arr)

<U32
['1' '2' '3.3' 'True']


In [10]:
lst = [10,20,30,40.7]
arr = np.array(lst)
arr = arr.astype(np.int32)
print(arr)
print(arr.dtype)
print(type(arr))

[10 20 30 40]
int32
<class 'numpy.ndarray'>


In [11]:
tpl = (1,2,3,4,5)
tpl = np.array(tpl)
print(type(tpl))
print(tpl.dtype)
print(tpl.ndim)
print(tpl.shape)

<class 'numpy.ndarray'>
int64
1
(5,)


In [12]:
st = {1,2,3,4}
st = np.array((st))
print(type(st))
print(st.dtype)
print(st.ndim)
print(st.shape)

<class 'numpy.ndarray'>
object
0
()


In [13]:
dc = {'a': 10, 'b': 20, 'c': 30}

key = dc.keys()
value = dc.values()
item = dc.items()

k = np.array(key)
print(type(k))
print(k)

v = np.array(value)
print(type(v))
print(v)

i = np.array(list(item))
print(type(i))
print(i)


<class 'numpy.ndarray'>
dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
dict_values([10, 20, 30])
<class 'numpy.ndarray'>
[['a' '10']
 ['b' '20']
 ['c' '30']]


In [14]:
arr = np.random.rand(3,3) 
print(arr)
print(arr.dtype)

[[0.50664658 0.05407862 0.35965329]
 [0.9824673  0.86374574 0.12014702]
 [0.01078693 0.55239798 0.32391544]]
float64


In [15]:
arr = np.random.randint(1, 10, (10,10))
print(arr)
print(arr.dtype)

[[3 6 4 5 6 7 4 4 9 9]
 [1 4 8 4 5 3 3 5 5 9]
 [1 9 2 4 7 5 2 2 5 4]
 [7 2 2 1 8 6 5 4 9 1]
 [1 5 6 7 5 7 7 1 6 1]
 [4 8 2 9 9 1 6 4 5 3]
 [9 7 3 6 3 4 1 3 8 1]
 [9 2 5 1 2 7 6 9 2 3]
 [8 7 5 1 3 9 2 9 8 7]
 [1 6 6 1 2 5 7 9 3 2]]
int32


In [16]:
arr = np.random.uniform(1, 10, (3,3))
print(arr)
print(arr.dtype)

[[6.81368862 1.84590699 8.51742244]
 [3.88453743 4.49639029 8.21414662]
 [1.8233011  5.64219402 4.34097815]]
float64


In [17]:
arr = np.arange(1,10, 3).reshape(3,)
print(arr)

[1 4 7]


In [18]:
arr = np.linspace(1, 10, 19)
print(arr)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [19]:
arr = np.logspace(0, 4, 5, base=8)
print(arr)

[1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]


In [20]:
arr = np.array([1,2,3,4,5])
print(arr[::])

[1 2 3 4 5]


In [21]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[0][1])

print(arr2[0:,0:2])

print(arr2[::-1,::-1])

2
[[1 2]
 [4 5]]
[[6 5 4]
 [3 2 1]]


In [22]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[::-1,::-1])

[[6 5 4]
 [3 2 1]]


In [23]:
arr2[:,:1]

array([[1],
       [4]])

In [24]:
arr = np.array([[1,2],
               [3,4]])

arr[0:1, 1:] == 300
print(arr)

[[1 2]
 [3 4]]


In [25]:
arr = np.array([1,2,3,4])
arr2 = arr[1:3].copy()
# arr2 = arr[1:3]


print(arr)
print(arr2)

arr2[1:2] = 100

print(arr)
print(arr2)

[1 2 3 4]
[2 3]
[1 2 3 4]
[  2 100]


In [26]:
lst = np.array([1,2,3,4,4])
values = lst[[2,3,3]]
print(lst)
print(values)

[1 2 3 4 4]
[3 4 4]


In [27]:
twod = np.array([[1,8,9],
                 [6,3,4]])
print(twod[1:,1:2])

[[3]]


In [28]:
print(lst[lst > 2])

[3 4 4]


In [29]:
arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)
    print(i)

1
2
3
[1 2 3]
4
5
6
[4 5 6]


In [30]:
arr = np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [31]:
data = [1,2,3,4,5]
temp_in_cel = np.array(data)
print(temp_in_cel * 1.8 + 32)

[33.8 35.6 37.4 39.2 41. ]


In [32]:
data = [1,2,3,4,5]
lap_times = np.array(data)
lap_times_in_minute = np.round((lap_times / 60).copy(),2)
print(lap_times)
print(lap_times_in_minute)

[1 2 3 4 5]
[0.02 0.03 0.05 0.07 0.08]


In [33]:
arr = np.random.randint(1,99, size=(10,5))
print(arr)

[[ 5  2 19  2 63]
 [ 5 22 30 57 61]
 [27 96 74 48 90]
 [82 18 83 54  4]
 [ 1 60 81 58 48]
 [85 60 22  8  7]
 [85  7 24 59 91]
 [60 34 44 82 80]
 [73 87 38 88 37]
 [61 54 31 86 21]]


In [34]:
print(arr.shape)
print(arr)
arr = arr.reshape(5,10) 
print(arr.shape)
print(arr)


(10, 5)
[[ 5  2 19  2 63]
 [ 5 22 30 57 61]
 [27 96 74 48 90]
 [82 18 83 54  4]
 [ 1 60 81 58 48]
 [85 60 22  8  7]
 [85  7 24 59 91]
 [60 34 44 82 80]
 [73 87 38 88 37]
 [61 54 31 86 21]]
(5, 10)
[[ 5  2 19  2 63  5 22 30 57 61]
 [27 96 74 48 90 82 18 83 54  4]
 [ 1 60 81 58 48 85 60 22  8  7]
 [85  7 24 59 91 60 34 44 82 80]
 [73 87 38 88 37 61 54 31 86 21]]


In [35]:
arr.ndim

2

In [36]:
flatt = arr.flatten()

In [37]:
flatt.ndim

1

In [38]:
print(arr)

[[ 5  2 19  2 63  5 22 30 57 61]
 [27 96 74 48 90 82 18 83 54  4]
 [ 1 60 81 58 48 85 60 22  8  7]
 [85  7 24 59 91 60 34 44 82 80]
 [73 87 38 88 37 61 54 31 86 21]]


In [39]:
print(flatt)

[ 5  2 19  2 63  5 22 30 57 61 27 96 74 48 90 82 18 83 54  4  1 60 81 58
 48 85 60 22  8  7 85  7 24 59 91 60 34 44 82 80 73 87 38 88 37 61 54 31
 86 21]


In [40]:
rav = np.ravel(arr, order='K')

In [41]:
print(rav)

[ 5  2 19  2 63  5 22 30 57 61 27 96 74 48 90 82 18 83 54  4  1 60 81 58
 48 85 60 22  8  7 85  7 24 59 91 60 34 44 82 80 73 87 38 88 37 61 54 31
 86 21]


In [44]:
a = np.random.randint(1, 10, (2,3))
b = np.random.randint(11, 20, (2,3))
print(a)
print(b)

[[8 5 6]
 [1 8 7]]
[[18 16 15]
 [15 18 14]]


In [45]:
con = np.concatenate((a, b), axis=1)
print(con)

[[ 8  5  6 18 16 15]
 [ 1  8  7 15 18 14]]


In [46]:
con = np.concatenate((a, b), axis=0)
print(con)

[[ 8  5  6]
 [ 1  8  7]
 [18 16 15]
 [15 18 14]]


In [47]:
mat = np.array([
    [1,2,3],
    [4,5,6]
])

transpost = mat.T
transpost

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
a = np.random.randint(1, 10, (9,))
print(a)

[4 5 7 7 3 7 9 2 1]


In [59]:
split_arr = np.array_split(a, 3) 
print(split_arr)

[array([4, 5, 7], dtype=int32), array([7, 3, 7], dtype=int32), array([9, 2, 1], dtype=int32)]


In [61]:
split_arr = np.split(a, 3)
print(split_arr)

[array([4, 5, 7], dtype=int32), array([7, 3, 7], dtype=int32), array([9, 2, 1], dtype=int32)]
