In [32]:
import numpy as np

In [33]:
arr = [1,2,3]
print(arr * 5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [34]:
arr = np.array([1,2,3])
print(arr * 5)

[ 5 10 15]


In [35]:
arr1 = np.array([1,2,3])
print(arr1.ndim)
print(arr1.dtype)
print(arr1.shape)

1
int64
(3,)


In [36]:
arr2 = np.array([[1,2,3],[1,2,3]])
print(arr2.ndim)
print(arr2.dtype)
print(arr2.shape)

2
int64
(2, 3)


In [37]:
arr3 = np.array([[[1,2], [3,4]], [[1,2],[3,4]]])
print(arr3.ndim)
print(arr3.dtype)
print(arr3.shape)

3
int64
(2, 2, 2)


In [38]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [39]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
dtypee.astype(np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [40]:
arr = np.array([1,'2', 3.3, True])
print(arr.dtype)
print(arr)

<U32
['1' '2' '3.3' 'True']


In [41]:
lst = [10,20,30,40.7]
arr = np.array(lst)
arr = arr.astype(np.int32)
print(arr)
print(arr.dtype)
print(type(arr))

[10 20 30 40]
int32
<class 'numpy.ndarray'>


In [42]:
tpl = (1,2,3,4,5)
tpl = np.array(tpl)
print(type(tpl))
print(tpl.dtype)
print(tpl.ndim)
print(tpl.shape)

<class 'numpy.ndarray'>
int64
1
(5,)


In [43]:
st = {1,2,3,4}
st = np.array((st))
print(type(st))
print(st.dtype)
print(st.ndim)
print(st.shape)

<class 'numpy.ndarray'>
object
0
()


In [44]:
dc = {'a': 10, 'b': 20, 'c': 30}

key = dc.keys()
value = dc.values()
item = dc.items()

k = np.array(key)
print(type(k))
print(k)

v = np.array(value)
print(type(v))
print(v)

i = np.array(list(item))
print(type(i))
print(i)


<class 'numpy.ndarray'>
dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
dict_values([10, 20, 30])
<class 'numpy.ndarray'>
[['a' '10']
 ['b' '20']
 ['c' '30']]


In [45]:
arr = np.random.rand(3,3) 
print(arr)
print(arr.dtype)

[[0.18255978 0.21238117 0.92816028]
 [0.05565669 0.34038518 0.54522406]
 [0.91419947 0.06619752 0.88047961]]
float64


In [46]:
arr = np.random.randint(1, 10, (10,10))
print(arr)
print(arr.dtype)

[[7 9 7 1 5 9 9 4 1 2]
 [9 7 2 4 7 9 6 4 2 5]
 [8 2 9 8 8 9 5 4 9 8]
 [8 7 4 8 6 7 9 3 5 7]
 [8 7 1 1 9 3 7 5 9 4]
 [7 6 8 3 7 6 3 1 3 1]
 [7 4 9 2 7 6 3 3 4 8]
 [5 9 4 9 8 6 4 4 9 2]
 [7 6 6 8 6 7 9 4 2 8]
 [2 2 7 6 9 2 3 4 1 6]]
int32


In [47]:
arr = np.random.uniform(1, 10, (3,3))
print(arr)
print(arr.dtype)

[[2.18784384 6.07261319 9.17099432]
 [1.94633521 1.47346909 8.69090461]
 [3.75418251 3.06512707 6.02194832]]
float64


In [48]:
arr = np.arange(1,10, 3).reshape(3,)
print(arr)

[1 4 7]


In [49]:
arr = np.linspace(1, 10, 19)
print(arr)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [50]:
arr = np.logspace(0, 4, 5, base=8)
print(arr)

[1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]


In [51]:
arr = np.array([1,2,3,4,5])
print(arr[::])

[1 2 3 4 5]


In [52]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[0][1])

print(arr2[0:,0:2])

print(arr2[::-1,::-1])

2
[[1 2]
 [4 5]]
[[6 5 4]
 [3 2 1]]


In [53]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[::-1,::-1])

[[6 5 4]
 [3 2 1]]


In [54]:
arr2[:,:1]

array([[1],
       [4]])

In [55]:
arr = np.array([[1,2],
               [3,4]])

arr[0:1, 1:] == 300
print(arr)

[[False]]
[[1 2]
 [3 4]]
