In [1]:
import numpy as np

In [2]:
arr = [1,2,3]
print(arr * 5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [3]:
arr = np.array([1,2,3])
print(arr * 5)

[ 5 10 15]


In [4]:
arr1 = np.array([1,2,3])
print(arr1.ndim)
print(arr1.dtype)
print(arr1.shape)

1
int64
(3,)


In [5]:
arr2 = np.array([[1,2,3],[1,2,3]])
print(arr2.ndim)
print(arr2.dtype)
print(arr2.shape)

2
int64
(2, 3)


In [6]:
arr3 = np.array([[[1,2], [3,4]], [[1,2],[3,4]]])
print(arr3.ndim)
print(arr3.dtype)
print(arr3.shape)

3
int64
(2, 2, 2)


In [7]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [8]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
dtypee.astype(np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [9]:
arr = np.array([1,'2', 3.3, True])
print(arr.dtype)
print(arr)

<U32
['1' '2' '3.3' 'True']


In [10]:
lst = [10,20,30,40.7]
arr = np.array(lst)
arr = arr.astype(np.int32)
print(arr)
print(arr.dtype)
print(type(arr))

[10 20 30 40]
int32
<class 'numpy.ndarray'>


In [11]:
tpl = (1,2,3,4,5)
tpl = np.array(tpl)
print(type(tpl))
print(tpl.dtype)
print(tpl.ndim)
print(tpl.shape)

<class 'numpy.ndarray'>
int64
1
(5,)


In [12]:
st = {1,2,3,4}
st = np.array((st))
print(type(st))
print(st.dtype)
print(st.ndim)
print(st.shape)

<class 'numpy.ndarray'>
object
0
()


In [13]:
dc = {'a': 10, 'b': 20, 'c': 30}

key = dc.keys()
value = dc.values()
item = dc.items()

k = np.array(key)
print(type(k))
print(k)

v = np.array(value)
print(type(v))
print(v)

i = np.array(list(item))
print(type(i))
print(i)


<class 'numpy.ndarray'>
dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
dict_values([10, 20, 30])
<class 'numpy.ndarray'>
[['a' '10']
 ['b' '20']
 ['c' '30']]


In [14]:
arr = np.random.rand(3,3) 
print(arr)
print(arr.dtype)

[[0.7013625  0.58911674 0.79714577]
 [0.44511662 0.90486169 0.340395  ]
 [0.63549523 0.37620597 0.43037056]]
float64


In [15]:
arr = np.random.randint(1, 10, (10,10))
print(arr)
print(arr.dtype)

[[5 5 3 8 2 2 2 8 7 6]
 [9 6 5 5 3 9 3 1 1 5]
 [6 7 9 6 7 1 2 2 7 2]
 [4 1 5 1 8 1 9 3 7 6]
 [6 8 5 5 2 3 7 6 9 2]
 [9 5 7 6 5 1 7 8 1 5]
 [1 3 4 7 9 3 6 5 9 9]
 [1 9 4 1 4 9 8 2 2 3]
 [3 2 5 8 4 5 9 2 2 7]
 [8 9 9 5 5 5 3 1 6 4]]
int32


In [16]:
arr = np.random.uniform(1, 10, (3,3))
print(arr)
print(arr.dtype)

[[9.50964004 1.37166205 6.00583735]
 [2.42668111 7.59437372 3.40444777]
 [9.99737036 5.27647148 5.67596132]]
float64


In [17]:
arr = np.arange(1,10, 3).reshape(3,)
print(arr)

[1 4 7]


In [18]:
arr = np.linspace(1, 10, 19)
print(arr)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [19]:
arr = np.logspace(0, 4, 5, base=8)
print(arr)

[1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]


In [20]:
arr = np.array([1,2,3,4,5])
print(arr[::])

[1 2 3 4 5]


In [21]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[0][1])

print(arr2[0:,0:2])

print(arr2[::-1,::-1])

2
[[1 2]
 [4 5]]
[[6 5 4]
 [3 2 1]]


In [22]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[::-1,::-1])

[[6 5 4]
 [3 2 1]]


In [23]:
arr2[:,:1]

array([[1],
       [4]])

In [24]:
arr = np.array([[1,2],
               [3,4]])

arr[0:1, 1:] == 300
print(arr)

[[1 2]
 [3 4]]


In [25]:
arr = np.array([1,2,3,4])
arr2 = arr[1:3].copy()
# arr2 = arr[1:3]


print(arr)
print(arr2)

arr2[1:2] = 100

print(arr)
print(arr2)

[1 2 3 4]
[2 3]
[1 2 3 4]
[  2 100]


In [26]:
lst = np.array([1,2,3,4,4])
values = lst[[2,3,3]]
print(lst)
print(values)

[1 2 3 4 4]
[3 4 4]


In [27]:
twod = np.array([[1,8,9],
                 [6,3,4]])
print(twod[1:,1:2])

[[3]]


In [28]:
print(lst[lst > 2])

[3 4 4]


In [29]:
arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)
    print(i)

1
2
3
[1 2 3]
4
5
6
[4 5 6]


In [30]:
arr = np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [31]:
data = [1,2,3,4,5]
temp_in_cel = np.array(data)
print(temp_in_cel * 1.8 + 32)

[33.8 35.6 37.4 39.2 41. ]


In [32]:
data = [1,2,3,4,5]
lap_times = np.array(data)
lap_times_in_minute = np.round((lap_times / 60).copy(),2)
print(lap_times)
print(lap_times_in_minute)

[1 2 3 4 5]
[0.02 0.03 0.05 0.07 0.08]


In [33]:
arr = np.random.randint(1,99, size=(10,5))
print(arr)

[[89  6 94 81 24]
 [12 12 15 10 42]
 [30 55 51 66 16]
 [43 49 30  6 31]
 [81 81 96 26  8]
 [55 22 93 15 35]
 [87 76 78 77 10]
 [22 97 89 71 15]
 [54 68 52 42 97]
 [91 26 91 68 36]]


In [34]:
print(arr.shape)
print(arr)
arr = arr.reshape(5,10) 
print(arr.shape)
print(arr)


(10, 5)
[[89  6 94 81 24]
 [12 12 15 10 42]
 [30 55 51 66 16]
 [43 49 30  6 31]
 [81 81 96 26  8]
 [55 22 93 15 35]
 [87 76 78 77 10]
 [22 97 89 71 15]
 [54 68 52 42 97]
 [91 26 91 68 36]]
(5, 10)
[[89  6 94 81 24 12 12 15 10 42]
 [30 55 51 66 16 43 49 30  6 31]
 [81 81 96 26  8 55 22 93 15 35]
 [87 76 78 77 10 22 97 89 71 15]
 [54 68 52 42 97 91 26 91 68 36]]


In [35]:
arr.ndim

2

In [36]:
flatt = arr.flatten()

In [37]:
flatt.ndim

1

In [38]:
print(arr)

[[89  6 94 81 24 12 12 15 10 42]
 [30 55 51 66 16 43 49 30  6 31]
 [81 81 96 26  8 55 22 93 15 35]
 [87 76 78 77 10 22 97 89 71 15]
 [54 68 52 42 97 91 26 91 68 36]]


In [39]:
print(flatt)

[89  6 94 81 24 12 12 15 10 42 30 55 51 66 16 43 49 30  6 31 81 81 96 26
  8 55 22 93 15 35 87 76 78 77 10 22 97 89 71 15 54 68 52 42 97 91 26 91
 68 36]


In [40]:
rav = np.ravel(arr, order='K')

In [41]:
print(rav)

[89  6 94 81 24 12 12 15 10 42 30 55 51 66 16 43 49 30  6 31 81 81 96 26
  8 55 22 93 15 35 87 76 78 77 10 22 97 89 71 15 54 68 52 42 97 91 26 91
 68 36]


In [42]:
a = np.random.randint(1, 10, (2,3))
b = np.random.randint(11, 20, (2,3))
print(a)
print(b)

[[5 5 2]
 [1 5 4]]
[[15 15 13]
 [19 14 13]]


In [43]:
con = np.concatenate((a, b), axis=1)
print(con)

[[ 5  5  2 15 15 13]
 [ 1  5  4 19 14 13]]


In [44]:
con = np.concatenate((a, b), axis=0)
print(con)

[[ 5  5  2]
 [ 1  5  4]
 [15 15 13]
 [19 14 13]]


In [45]:
mat = np.array([
    [1,2,3],
    [4,5,6]
])

transpost = mat.T
transpost

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
a = np.random.randint(1, 10, (9,))
print(a)

[1 3 3 4 6 5 1 4 4]


In [47]:
split_arr = np.array_split(a, 3) 
print(split_arr)

[array([1, 3, 3], dtype=int32), array([4, 6, 5], dtype=int32), array([1, 4, 4], dtype=int32)]


In [48]:
split_arr = np.split(a, 3)
print(split_arr)

[array([1, 3, 3], dtype=int32), array([4, 6, 5], dtype=int32), array([1, 4, 4], dtype=int32)]


In [49]:
a

array([1, 3, 3, 4, 6, 5, 1, 4, 4], dtype=int32)

In [50]:
sinn = np.sin(a)
sinn

array([ 0.84147098,  0.14112001,  0.14112001, -0.7568025 , -0.2794155 ,
       -0.95892427,  0.84147098, -0.7568025 , -0.7568025 ])

In [51]:
coss = np.cos(a)
coss

array([ 0.54030231, -0.9899925 , -0.9899925 , -0.65364362,  0.96017029,
        0.28366219,  0.54030231, -0.65364362, -0.65364362])

In [52]:
degtored = np.rad2deg(a)
degtored

array([ 57.29577951, 171.88733854, 171.88733854, 229.18311805,
       343.77467708, 286.47889757,  57.29577951, 229.18311805,
       229.18311805])

In [53]:
ten_base_log = np.log10(a)
ten_base_log

array([0.        , 0.47712125, 0.47712125, 0.60205999, 0.77815125,
       0.69897   , 0.        , 0.60205999, 0.60205999])

In [54]:
two_base_log = np.log2(a)
print(two_base_log)

[0.         1.5849625  1.5849625  2.         2.5849625  2.32192809
 0.         2.         2.        ]


In [55]:
sqrt = np.sqrt(a)
print(sqrt)

[1.         1.73205081 1.73205081 2.         2.44948974 2.23606798
 1.         2.         2.        ]


In [56]:
x = np.array([10,800,16,100])
y = np.array([2,3,4,5])
print(x < y)
print(x > y)
print(x == y)


[False False False False]
[ True  True  True  True]
[False False False False]


In [57]:
print(np.all(x>y))

True


In [58]:
x

array([ 10, 800,  16, 100])

In [59]:
z = x.copy()

In [60]:
z

array([ 10, 800,  16, 100])

In [61]:
z.sort()
z

array([ 10,  16, 100, 800])

In [62]:
x

array([ 10, 800,  16, 100])

In [63]:
x

array([ 10, 800,  16, 100])

In [64]:
z

array([ 10,  16, 100, 800])

In [65]:
sort_arr = np.sort(x)
sort_arr

array([ 10,  16, 100, 800])

In [66]:
x

array([ 10, 800,  16, 100])

In [67]:
z

array([ 10,  16, 100, 800])

In [68]:
mat = np.array([[1,30,9],
               [5,4,8]])
hor_sort = np.sort(mat, axis=1)
print(hor_sort)
print()
ver_sort = np.sort(mat, axis=0)
print(ver_sort)

[[ 1  9 30]
 [ 4  5  8]]

[[ 1  4  8]
 [ 5 30  9]]


In [69]:
x

array([ 10, 800,  16, 100])

In [70]:
print(x)

[ 10 800  16 100]


In [71]:
index = np.where(x>8)
print(index)


(array([0, 1, 2, 3]),)


In [72]:
index = np.where(x>8, x, 0)
print(index)


[ 10 800  16 100]


In [73]:
mat

array([[ 1, 30,  9],
       [ 5,  4,  8]])

In [74]:
index = np.where(mat > 5)

In [75]:
index

(array([0, 0, 1]), array([1, 2, 2]))

In [76]:
index = np.where(mat<8, mat, 0)
print(index)

[[1 0 0]
 [5 4 0]]


In [77]:
x

array([ 10, 800,  16, 100])

In [78]:
index = np.argmax(x)
print(index)
print(x[index])

1
800


In [79]:
index = np.argmin(x)
print(index)
print(x[index])

0
10


In [80]:
rand = np.random.randint(1,100,size=100)

In [81]:
print(rand)

[11 18 59 26 97 66 12 33 45 62 24 72 17 94 16 24 82 22 93 42 24 76 36 49
 34 28  5 57 12 70 26 36  1 50 58 73 47 82 55  5  7 56 61 98 88 53 89 52
 54 41 55 14 59 24  3 84 36 65 24  8 52 93 58 33 27 75 16 21 71 10 18 43
 29 67 46 12 56 15  9 40 54 57 43 31 60  7 88 82 87 72 94 14 86 94 55 56
 30 36 45 57]


In [82]:
count_number = np.count_nonzero(rand==70)
print(count_number)

1


In [83]:
uniq = np.unique(rand, return_counts = True)
print(uniq)

(array([ 1,  3,  5,  7,  8,  9, 10, 11, 12, 14, 15, 16, 17, 18, 21, 22, 24,
       26, 27, 28, 29, 30, 31, 33, 34, 36, 40, 41, 42, 43, 45, 46, 47, 49,
       50, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 65, 66, 67, 70, 71,
       72, 73, 75, 76, 82, 84, 86, 87, 88, 89, 93, 94, 97, 98],
      dtype=int32), array([1, 1, 2, 2, 1, 1, 1, 1, 3, 2, 1, 2, 1, 2, 1, 1, 5, 2, 1, 1, 1, 1,
       1, 2, 1, 4, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 3, 3, 3, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1, 2, 3, 1, 1]))


In [91]:
data = np.genfromtxt('sunject_number.csv', delimiter=',',skip_header=True)

In [93]:
print(data)

[[74. 82. 78.]
 [69. 71. 65.]
 [92. 88. 90.]
 [58. 63. 54.]
 [84. 76. 81.]
 [75. 69. 72.]
 [89. 91. 95.]
 [62. 57. 60.]
 [86. 79. 84.]
 [70. 73. 67.]
 [90. 85. 88.]
 [52. 55. 49.]
 [78. 80. 76.]
 [71. 66. 69.]
 [91. 94. 92.]
 [64. 61. 58.]
 [80. 77. 83.]
 [68. 74. 71.]
 [87. 89. 86.]
 [65. 59. 63.]
 [77. 81. 79.]
 [57. 60. 55.]
 [93. 87. 91.]
 [70. 72. 68.]
 [76. 78. 74.]
 [85. 84. 82.]
 [61. 56. 59.]
 [88. 90. 87.]
 [67. 64. 66.]
 [94. 95. 93.]
 [73. 75. 70.]
 [81. 79. 77.]
 [60. 58. 62.]
 [86. 83. 85.]
 [59. 62. 57.]
 [90. 92. 89.]
 [66. 68. 64.]
 [82. 78. 80.]
 [55. 57. 53.]
 [95. 96. 94.]
 [74. 70. 73.]
 [63. 65. 61.]
 [83. 86. 84.]
 [58. 54. 56.]
 [89. 87. 88.]
 [76. 77. 75.]
 [68. 69. 67.]
 [92. 93. 91.]
 [73. 71. 72.]
 [78. 80. 79.]]


In [94]:
math_marks = data[:, :1]

In [99]:
print(math_marks)

[[74.]
 [69.]
 [92.]
 [58.]
 [84.]
 [75.]
 [89.]
 [62.]
 [86.]
 [70.]
 [90.]
 [52.]
 [78.]
 [71.]
 [91.]
 [64.]
 [80.]
 [68.]
 [87.]
 [65.]
 [77.]
 [57.]
 [93.]
 [70.]
 [76.]
 [85.]
 [61.]
 [88.]
 [67.]
 [94.]
 [73.]
 [81.]
 [60.]
 [86.]
 [59.]
 [90.]
 [66.]
 [82.]
 [55.]
 [95.]
 [74.]
 [63.]
 [83.]
 [58.]
 [89.]
 [76.]
 [68.]
 [92.]
 [73.]
 [78.]]


In [102]:
print(math_marks.max())
print(math_marks.min())
print(math_marks.mean())
print(np.median(math_marks))
print(math_marks.std())




95.0
52.0
75.48
75.5
11.899983193265443


In [106]:
study_hours = np.array([2,4,5,7,8])
exam_scores = np.array([65,75,78,88,92])

data = np.array([study_hours, exam_scores])
print(data)

correlation = np.corrcoef(data)
print(f"Correlation matrix: \n {correlation}")

[[ 2  4  5  7  8]
 [65 75 78 88 92]]
Correlation matrix: 
 [[1.         0.99859154]
 [0.99859154 1.        ]]


In [107]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([
    [7,8],
    [9, 10],
    [11,12]
])

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [109]:
matt_gun = np.dot(a,b)
print(matt_gun)

[[ 58  64]
 [139 154]]


In [110]:
trace = np.trace(a)
trace2 = np.trace(b)
print(trace, trace2)


6 17


In [115]:
sq_mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(sq_mat.shape)

det_sq_mat = np.linalg.det(sq_mat)
print(det_sq_mat)

det_sq_mat_rank = np.linalg.matrix_rank(sq_mat)
print(det_sq_mat_rank)

(3, 3)
-9.51619735392994e-16
2
