In [1]:
import numpy as np

In [2]:
arr = [1,2,3]
print(arr * 5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [3]:
arr = np.array([1,2,3])
print(arr * 5)

[ 5 10 15]


In [4]:
arr1 = np.array([1,2,3])
print(arr1.ndim)
print(arr1.dtype)
print(arr1.shape)

1
int64
(3,)


In [5]:
arr2 = np.array([[1,2,3],[1,2,3]])
print(arr2.ndim)
print(arr2.dtype)
print(arr2.shape)

2
int64
(2, 3)


In [6]:
arr3 = np.array([[[1,2], [3,4]], [[1,2],[3,4]]])
print(arr3.ndim)
print(arr3.dtype)
print(arr3.shape)

3
int64
(2, 2, 2)


In [7]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [8]:
dtypee = np.array([1,2,3.4, '5'], dtype=np.float16)
dtypee.astype(np.float16)
print(dtypee)
print(dtypee.dtype)

[1.  2.  3.4 5. ]
float16


In [9]:
arr = np.array([1,'2', 3.3, True])
print(arr.dtype)
print(arr)

<U32
['1' '2' '3.3' 'True']


In [10]:
lst = [10,20,30,40.7]
arr = np.array(lst)
arr = arr.astype(np.int32)
print(arr)
print(arr.dtype)
print(type(arr))

[10 20 30 40]
int32
<class 'numpy.ndarray'>


In [11]:
tpl = (1,2,3,4,5)
tpl = np.array(tpl)
print(type(tpl))
print(tpl.dtype)
print(tpl.ndim)
print(tpl.shape)

<class 'numpy.ndarray'>
int64
1
(5,)


In [12]:
st = {1,2,3,4}
st = np.array((st))
print(type(st))
print(st.dtype)
print(st.ndim)
print(st.shape)

<class 'numpy.ndarray'>
object
0
()


In [13]:
dc = {'a': 10, 'b': 20, 'c': 30}

key = dc.keys()
value = dc.values()
item = dc.items()

k = np.array(key)
print(type(k))
print(k)

v = np.array(value)
print(type(v))
print(v)

i = np.array(list(item))
print(type(i))
print(i)


<class 'numpy.ndarray'>
dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
dict_values([10, 20, 30])
<class 'numpy.ndarray'>
[['a' '10']
 ['b' '20']
 ['c' '30']]


In [14]:
arr = np.random.rand(3,3) 
print(arr)
print(arr.dtype)

[[0.35805626 0.59442982 0.43866401]
 [0.24315275 0.62944904 0.85173572]
 [0.35302335 0.2949218  0.05676945]]
float64


In [15]:
arr = np.random.randint(1, 10, (10,10))
print(arr)
print(arr.dtype)

[[8 7 2 9 6 3 5 1 5 7]
 [4 9 7 5 7 3 5 4 4 2]
 [9 8 3 6 8 2 2 5 2 9]
 [6 7 1 7 1 2 2 2 5 9]
 [1 1 5 3 2 7 9 4 1 3]
 [2 2 3 6 5 1 2 7 3 6]
 [7 8 2 5 1 5 2 3 8 6]
 [8 8 5 9 3 4 3 1 4 2]
 [5 2 6 3 3 1 8 4 9 5]
 [3 4 2 7 5 8 7 9 1 6]]
int32


In [16]:
arr = np.random.uniform(1, 10, (3,3))
print(arr)
print(arr.dtype)

[[4.76900191 6.14324521 2.45826168]
 [8.16579075 2.80185752 9.18320422]
 [7.90252888 4.21669466 4.25390264]]
float64


In [17]:
arr = np.arange(1,10, 3).reshape(3,)
print(arr)

[1 4 7]


In [18]:
arr = np.linspace(1, 10, 19)
print(arr)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [19]:
arr = np.logspace(0, 4, 5, base=8)
print(arr)

[1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]


In [20]:
arr = np.array([1,2,3,4,5])
print(arr[::])

[1 2 3 4 5]


In [21]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[0][1])

print(arr2[0:,0:2])

print(arr2[::-1,::-1])

2
[[1 2]
 [4 5]]
[[6 5 4]
 [3 2 1]]


In [22]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2[::-1,::-1])

[[6 5 4]
 [3 2 1]]
